#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* RT-Thread Kernel */
#define RT_CPUS_NR 1
#define RT_NAME_MAX 16
#define RT_ALIGN_SIZE 4
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 100
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HEAP
#define RT_USING_COMPONENTS_INIT
#define IDLE_THREAD_STACK_SIZE 512
#define RT_CONSOLEBUF_SIZE 256
#define RT_BACKTRACE_LEVEL_MAX_NR 32
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 2048

/* Device drivers */
#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_CONSOLE_DEVICE_NAME "uart0"

/* Shell */

/* Drivers */
#define BSP_USING_UART
#define BSP_USING_UART0

#define SOC_MPS2_AN500

#endif
