import os
from building import *

cwd = GetCurrentDir()

# build startup assembly
objs = DefineGroup('Startup', ['startup_gcc.S'], depend=[''])

# enter subdirectories
for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
