import os
from building import *
import building

cwd = GetCurrentDir()
objs = []
env = building.Env
list = os.listdir(cwd)

if os.path.exists(os.path.join(cwd, 'startup_gcc.S')):
    objs.append(env.Object('startup_gcc.S'))

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
